<a href="https://colab.research.google.com/github/ctrlc0ctrlv/deep_learning_2018-19/blob/master/%5Bhomework%2Cbasic%5Dnumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>

<h3 style="text-align: center;"><b>Физтех-Школа Прикладной математики и информатики (ФПМИ) МФТИ</b></h3>

---

## Домашнее задание: библиотека Numpy и линейная алгебра. Решение


In [0]:
import numpy as np
import random
import scipy.stats as sps

### Numpy

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [27]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print(a.ndim)
print(b.ndim)

print(a.shape)
print(b.shape)
# ========
print(a)
print(b)

2
2
(100, 100)
(100, 100)
[[0.81424428 0.99590306 0.79968516 ... 0.18851559 0.82601164 0.49667101]
 [0.05922274 0.40672893 0.57934116 ... 0.45872401 0.66480129 0.93757423]
 [0.6890501  0.66841761 0.97891285 ... 0.51447105 0.60059369 0.07203088]
 ...
 [0.44335704 0.69377725 0.00319114 ... 0.38488764 0.20860297 0.25232979]
 [0.53839209 0.37851971 0.30605249 ... 0.49101539 0.48639394 0.29503926]
 [0.42119966 0.72000764 0.7603434  ... 0.83697821 0.59280058 0.39659178]]
[[0.85981645 0.58023567 0.73982834 ... 0.56086123 0.10552016 0.03796219]
 [0.27802358 0.17094903 0.48408576 ... 0.75838095 0.17312698 0.80549313]
 [0.12691658 0.86199888 0.44893752 ... 0.22924551 0.66639961 0.80550079]
 ...
 [0.31629287 0.66894525 0.5222366  ... 0.13678249 0.82815201 0.64963706]
 [0.49418888 0.04750111 0.87519197 ... 0.83327073 0.32581045 0.2589007 ]
 [0.98531229 0.0977167  0.50373549 ... 0.42537138 0.15646462 0.28275884]]


In [28]:
#a = np.array([[2, 3], [-5, 6]])
#b = np.array([[1, -2], [3, 4]])

def mult(a, b):
    # здесь напишите перемножение матриц без 
    # использования NumPy и выведите результат
    """
    param first: list of "size" lists, each contains "size" floats
    param first: list of "size" lists, each contains "size" floats
    """
    size = len(a)
    result = [[0 for i in range(size)] for j in range(size)]
    for i in range(size):
        for j in range(size):
            for x in range(size):
                result[i][j] += a[i][x] * b[x][j]

    #print(np.array(result))
    return result

mult(a, b)

[[26.850063378044517,
  22.299857341096498,
  26.673890064891566,
  29.033409949284692,
  24.33467864402511,
  27.117432188629987,
  26.829239975410353,
  25.550218823630846,
  28.311925944230342,
  29.574359501309345,
  23.48381519655567,
  25.44720087708749,
  27.93852416925751,
  29.03856045978866,
  27.991005486859375,
  25.910473078790503,
  28.138058413296456,
  22.67947149107258,
  27.265789260769154,
  26.40970099046864,
  23.380030143597715,
  22.952955850848344,
  28.684068658628902,
  25.15087064970169,
  25.923848344330494,
  28.44771633599363,
  25.04827456755581,
  26.319975151849068,
  24.39643160668325,
  24.704083799345792,
  28.25426829270221,
  30.344806025576933,
  26.129385197216017,
  29.27799420896942,
  26.36821390296566,
  29.94568047990289,
  25.814813952789045,
  26.704504583392893,
  26.78457056546821,
  28.399563852497828,
  24.748973039547693,
  24.330835425062457,
  30.811656203125736,
  27.913306619634753,
  26.87656716641345,
  27.15163550152821,
  27.5

In [29]:
def np_mult(a, b):
    # здесь напишите перемножение матриц с
    # использованием NumPy и выведите результат
    return(np.dot(a, b))
print(np_mult(a,b))

[[26.85006338 22.29985734 26.67389006 ... 24.74930948 27.96261862
  27.72917206]
 [25.16918795 24.08979762 25.00082395 ... 24.40938803 29.15182619
  26.93306485]
 [27.21869188 24.71961551 25.93021921 ... 26.74141714 28.74661468
  26.96254212]
 ...
 [24.06335846 23.20411963 24.19125602 ... 25.23038633 25.75828184
  25.58398068]
 [23.38074754 20.81446855 24.70362483 ... 21.47070034 26.57997381
  24.88720363]
 [28.1318124  28.23922274 29.40595748 ... 28.11508969 31.22889466
  31.69741176]]


In [30]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 891 ms, sys: 3.82 ms, total: 894 ms
Wall time: 895 ms


In [31]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 1.5 ms, sys: 1.04 ms, total: 2.55 ms
Wall time: 2.65 ms


In [32]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.3791634501103545e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [39]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.34970264 0.99119377 0.53074633] [0.48074462 0.38778154 0.99993848]


In [38]:
def scalar_product(a,b):
    return sum(a[i]*b[i] for i in range(3))
scalar_product(a,b)

0.4902854604915772

In [35]:
def np_scalar_product(a,b):
    return np.inner(a, b)
np_scalar_product(a,b)

0.4902854604915772

In [40]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 26 µs, sys: 3 µs, total: 29 µs
Wall time: 31.7 µs
CPU times: user 39 µs, sys: 0 ns, total: 39 µs
Wall time: 42.4 µs


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

------------------

**Ответ:** Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [48]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[9, 9, 9, 8, 8],
       [1, 9, 5, 3, 9],
       [8, 6, 8, 8, 4],
       [2, 1, 2, 2, 3],
       [1, 3, 5, 5, 4]])

In [50]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
    x = a[np.arange(5), np.arange(5)]
    print(sum(x[np.where(x % 2 == 0)]))
np_diag_2k(a)

14


In [51]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

14
CPU times: user 650 µs, sys: 975 µs, total: 1.62 ms
Wall time: 1.38 ms


### Задание 4
Напишите функцию, которая по данной последовательности $\{A_i\}_{i=1}^n$ строит последовательность $S_n$, где $S_k = \frac{A_1 + ... + A_k}{k}$.  

In [0]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(A):
    return #YOUR CODE

In [54]:
# зададим некоторую последовательность и проверим ее на ваших функциях. 
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3) 

%time S2 = np_sec_av(A)

CPU times: user 5 µs, sys: 0 ns, total: 5 µs
Wall time: 8.34 µs


### Задание 5

​
Задан двумерный массив $X$. Для каждой строчки массива X необходимо сделать следующее преобразование.

Пусть дана строчка x. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число a (значение по умолчанию a=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив xс преобразованным xи вывести.

Напишите функцию, которая выполняет данное преобразование для каждой строчки двумерного массива X. Массив X при этом должен остаться без изменений.

Используйте библиотеку numpy.

Пример:
$X = [[100,200,300,400,500]]$ -> $[[100,a,300,a,500]]$ -> $[[500^3,a,300^3,a,100^3]]$ -> склеиваем -> $[[100,200,300,400,500,500^3,a,300^3,a,100^3]]$

​

In [135]:
# функция, решающая задачу с помощью NumPy
from copy import copy
def np_transformation(X, a=1):
    result = np.array([], dtype=type(X))
    for x in X:
        Y = np.copy(x)
        Y[1::2] = a
        Y[0::2] **=3
        Y = Y[::-1]
        print(np.concatenate([x, Y]))
        result = list(result).append(np.array(np.concatenate([x, Y])))
    return result
print(np_transformation(X, a=1))


[  1   2   3   4   5 125   1  27   1   1]
[  1   2   3   4   5 125   1  27   1   1]


TypeError: ignored

In [126]:
X = np.array([[i for i in range(1, 6)], [j for j in range(1, 6)]])
print(X)
# функция должна работать ~ в 20 раз быстрее, чем без Numpy 
%time S2 = np_transformation(X, 1)

[[1 2 3 4 5]
 [1 2 3 4 5]]
[  1   2   3   4   5 125   1  27   1   1]
[  1   2   3   4   5 125   1  27   1   1]
CPU times: user 598 µs, sys: 0 ns, total: 598 µs
Wall time: 604 µs


### Задание 6
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить. 

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [0]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    #YOUR CODE

In [0]:
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

%time x, num = np_encode(X)

CPU times: user 51 µs, sys: 2 µs, total: 53 µs
Wall time: 58.7 µs
