<a href="https://colab.research.google.com/github/ctrlc0ctrlv/deep_learning_2018-19/blob/master/%5Bhomework%2Cbasic%5Dnumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>

<h3 style="text-align: center;"><b>Физтех-Школа Прикладной математики и информатики (ФПМИ) МФТИ</b></h3>

---

## Домашнее задание: библиотека Numpy и линейная алгебра. Решение


In [0]:
import numpy as np
import random
import scipy.stats as sps

### Numpy

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [5]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print(a.ndim)
print(b.ndim)

print(a.shape)
print(b.shape)
# ========
print(a)
print(b)

2
2
(100, 100)
(100, 100)
[[0.78747806 0.88735424 0.70700114 ... 0.328473   0.55609543 0.09021991]
 [0.27179782 0.16782158 0.59938241 ... 0.48262444 0.52336043 0.29251176]
 [0.44117227 0.62815955 0.45237706 ... 0.41082677 0.58234064 0.14999296]
 ...
 [0.58478677 0.18271627 0.33713174 ... 0.00655878 0.19193168 0.61993865]
 [0.03646848 0.4641248  0.47276627 ... 0.05771266 0.81100578 0.69431937]
 [0.5006213  0.5760932  0.14631873 ... 0.04591502 0.68065947 0.22873955]]
[[0.21146809 0.04006293 0.52036063 ... 0.81061826 0.34424805 0.53095775]
 [0.21951997 0.25360896 0.28369424 ... 0.43228554 0.300863   0.68292796]
 [0.09088956 0.91575569 0.66719868 ... 0.98007042 0.17903455 0.80113028]
 ...
 [0.92663694 0.72117779 0.15813931 ... 0.46079186 0.96886458 0.23712974]
 [0.00436775 0.52641104 0.15418013 ... 0.02648574 0.92699695 0.98084679]
 [0.72580376 0.75342596 0.04929832 ... 0.80237872 0.43052163 0.92274512]]


In [0]:
def mult(a, b):
    # здесь напишите перемножение матриц без 
    # использования NumPy и выведите результат

In [0]:
def np_mult(a, b):
    # здесь напишите перемножение матриц с
    # использованием NumPy и выведите результат
    return(np.dot(a, b))

In [0]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 812 ms, sys: 7.61 ms, total: 820 ms
Wall time: 821 ms


In [0]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 1.27 ms, sys: 0 ns, total: 1.27 ms
Wall time: 587 µs


In [0]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.553246420371579e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [0]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.82238967 0.60895342 0.18699693] [0.10087098 0.31786346 0.05313135]


In [0]:
def scalar_product(a,b):
    #YOUR CODE

In [0]:
def np_scalar_product(a,b):
    #YOUR CODE

In [0]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 20 µs, sys: 1 µs, total: 21 µs
Wall time: 24.1 µs
CPU times: user 1.71 ms, sys: 66 µs, total: 1.78 ms
Wall time: 20.8 ms


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

------------------

**Ответ:** Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [0]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
    #YOUR CODE

In [0]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[4, 6, 1, 5, 5],
       [9, 2, 6, 7, 4],
       [9, 2, 8, 3, 7],
       [7, 6, 2, 4, 7],
       [5, 9, 7, 6, 9]])

In [0]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 107 µs, sys: 4 µs, total: 111 µs
Wall time: 118 µs


18

### Задание 4
Напишите функцию, которая по данной последовательности $\{A_i\}_{i=1}^n$ строит последовательность $S_n$, где $S_k = \frac{A_1 + ... + A_k}{k}$.  

In [0]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(A):
    return #YOUR CODE

In [0]:
# зададим некоторую последовательность и проверим ее на ваших функциях. 
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3) 

%time S2 = np_sec_av(A)

CPU times: user 616 µs, sys: 0 ns, total: 616 µs
Wall time: 507 µs


### Задание 5

​
Задан двумерный массив $X$. Для каждой строчки массива X необходимо сделать следующее преобразование.

Пусть дана строчка x. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число a (значение по умолчанию a=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив xс преобразованным xи вывести.

Напишите функцию, которая выполняет данное преобразование для каждой строчки двумерного массива X. Массив X при этом должен остаться без изменений.

Используйте библиотеку numpy.

Пример:
$X = [[100,200,300,400,500]]$ -> $[[100,a,300,a,500]]$ -> $[[500^3,a,300^3,a,100^3]]$ -> склеиваем -> $[[100,200,300,400,500,500^3,a,300^3,a,100^3]]$

​

In [0]:
# функция, решающая задачу с помощью NumPy
from copy import copy
def np_transformation(X, a=1):
    #YOUR CODE

In [0]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy 
%time S2 = np_transformation(X, 5)

CPU times: user 159 µs, sys: 0 ns, total: 159 µs
Wall time: 183 µs


### Задание 6
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить. 

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [0]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    #YOUR CODE

In [0]:
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

%time x, num = np_encode(X)

CPU times: user 51 µs, sys: 2 µs, total: 53 µs
Wall time: 58.7 µs
